### ISSUE TITLE
2.3.1 and 2.3.2 have broken dependencies

### ISSUE THREAD

**Issue by tvdeyen** [activerecord-hackery/ransack#1098]
Hey. Great work with Ransack. 

It seems you released a new version of Ransack that was meant to raise polyamorous version, but the latter has never been released. Currently you cannot bundle either ransack 2.3.1 nor 2.3.2. The latest released version on rubygems of polyamorous is 2.3.0. Bundler cannot find it. 

Also it seems that you released the removal of Rails 5.0 and 5.1 in 2.3.1 (a patch level release). Was this a mistake or intentional? Not that I am a huge semver fan, but this seems odd to me. 

The pressing issue here is that currently you cannot bundle ransack. As you can see in this PR https://github.com/AlchemyCMS/alchemy_cms/pull/1711

IMO you should release a 2.3.3 that reverts the changes of 2.3.1 and 2.3.2 and release a 3.0.0. (Please do not yank gems. This will cause even more issues for people using CIs). Also please do not forget to also release polyamorous with ransack, since they are separated gems now.

Thanks.

**Comment by tvdeyen** [comment]
> Also it seems that you released the removal of Rails 5.0 and 5.1 in 2.3.1 (a patch level release). Was this a mistake or intentional? Not that I am a huge semver fan, but this seems odd to me.

Disclaimer: I read this from the changelog and did not tested this with code. Maybe I am wrong here, but the changelog tells it that way

**Comment by seanfcarroll** [comment]
Hi @tvdeyen thanks very much for your message. You have some good points, I will look after it this evening.

I was under the impression that Polyamorous had been completely imported into the Ransack, as it has been archived. If Ransack is in fact pointing to still pointing to the external Polyamorous I will update it. 

https://github.com/activerecord-hackery/ransack/tree/master/polyamorous/lib/polyamorous

Perhaps I need to publish Polyamorous from within Ransack? If this is the case I'll reverse the integration until it can be completely imported properly.

Thanks.

**Comment by tvdeyen** [comment]
As far as I can tell polyamorous has a separate gemspec now (#1002). That means it has to be build and pushed to rubygems separately, as gems are just packaged files uploaded. 

I also saw that the ransack gem [still includes all files from the git repo](https://github.com/activerecord-hackery/ransack/blob/master/ransack.gemspec#L22), meaning that polyamorous is now shipped twice - once in the ransack gem package and once with polyamorous itself.

**Comment by seanfcarroll** [comment]
Yes I can see that. I’ll clé an it up, in the meantime please pin your code to 2.3.0

**Comment by seanfcarroll** [comment]
@tvdeyen please see https://github.com/activerecord-hackery/ransack/issues/1099 

I think this is the way forward. Afterwards we can do some refactoring and add new features to Ransack, but let's get the 6.0 work done.

**Comment by gregmolnar** [comment]
Polyamorous stayed a separate gem, but the files are in the same repository, so issues can be managed at one place. I kept it a separate gem to make it possible to use it as a dependency without relying on ransack as well. Like what baby_squeel  does.
The only caveat is, ransack and polyamorous needs to be released together, because they depend on being on the same version, but that can be easily solved while keeping the current structure.

**Comment by seanfcarroll** [comment]
Thanks @gregmolnar I had forgotten about baby_squeel. 

It doesn't seem like the project is that active https://github.com/rzane/baby_squeel/commits/master

I think Ransack needs a serious refactor, and the first step is to properly internalize Polyamorous (as a module). It will possibly need to be extended to fix these 6.0 issues. Also Polyamorous was never intended to be a shared gem, and wasn't documented etc. I think we really need to break from the past and modernize Ransack. Unfortunately there has only been a few of us contributing to the codebase.

I've posted a job on Upwork to handle these issues, and have already made an offer to a contractor https://www.upwork.com/ab/applicants/1215911323418488832/job-details. 

I would prefer to continue down this path. 

By the way, is anyone else having problems with 2.3.2? It's bundling fine for me for Rails 5.2.

```
GIT
  remote: git://github.com/activerecord-hackery/ransack.git
  revision: 901c1f262adca8e66f9311c7a0e4cd3cb02a277c
  specs:
    polyamorous (2.3.2)
      activerecord (>= 5.2.1)
    ransack (2.3.2)
      activerecord (>= 5.2.1)
      activesupport (>= 5.2.1)
      i18n
      polyamorous (= 2.3.2)
```

CC @mohdsameer

**Comment by seanfcarroll** [comment]
@deivid-rodriguez ah that makes sense. Thank you.

**Comment by gregmolnar** [comment]
To fix this issue we just need to release the 2 polyamorous version by the way. I will do so shortly.

**Comment by gregmolnar** [comment]
I pushed the missing polyamorous version, so everyone should be able to bundle now. As a follow up, I will create a PR to change the how we handle the polyamorous dependency, so it can have a separate version from ransack.

**Comment by seanfcarroll** [comment]
Thanks for trying @gregmolnar

**Comment by gregmolnar** [comment]
Here is the PR: https://github.com/activerecord-hackery/ransack/pull/1101
I think this one can be closed. @tvdeyen please ping me if it still doesn't work.

**Comment by tvdeyen** [comment]
Thanks @gregmolnar for releasing the gems.

There are still two issues remaining

> Also it seems that you released the removal of Rails 5.0 and 5.1 in 2.3.1 (a patch level release). Was this a mistake or intentional? Not that I am a huge semver fan, but this seems odd to me.

and

> I also saw that the ransack gem still includes all files from the git repo, meaning that polyamorous is now shipped twice - once in the ransack gem package and once with polyamorous itself.

I will create two individual issues, ok?

**Comment by gregmolnar** [comment]
@tvdeyen it would be great if you would open 2 separate issues for those. Thank you!
